### PR TITLE
[update] Adding functions to fetch statistics from OBIS

### PR DESCRIPTION
**Pull request by ayushanand18**
## Overview
This PR aims to add functions to gather statistics from OBIS (using the `statistics/` endpoint).

These functions just fetch the data as JSON objects which can be used to do visualizations later.

## Changes Introduced
```shell
function get_records: Get basic statistics for occurrence records.
function get_qc: Get a QC summary, including missing or invalid values, number of records on land, number of non marine records and number of records without Aphia ID.
function get_env: Get number of records per SST, SSS or depth bin.
function get_years: Get number of presence records per year.
function get_composition: Get an overview of taxonomic composition.
function get_outliers: Get SST and SSS distribution quartiles.
```
Thanks!

### CODE REVIEW

**Comment by ayushanand18** [comment]
The tests are failing because of 0% coverage, I'll bring in the tests in the next PR.

**Comment by 7yl4r** [comment]
Is this using part of the OBIS API? Should we consider including this in pyobis instead of here?

**Comment by ayushanand18** [comment]
> Is this using part of the OBIS API? Should we consider including this in pyobis instead of here?

Yes, these functions essentially ping to the OBIS API. I thought that since the other endpoints were planned to undergo major changes, including `/statistics/`, so I kept it here because this package is more dynamic. [Ref discussion here](https://github.com/iobis/pyobis/pull/8#issuecomment-1084317926). Please suggest.

**Comment by 7yl4r** [comment]
Thank you for the clarification. That makes sense. :+1:

**Pull request merged**
